let answer1 = document.getElementById('answer1');
let answer2 = document.getElementById('answer2');
let answer3 = document.getElementById('answer3');
let answer4 = document.getElementById('answer4');
let answer5 = document.getElementById('answer5');
let question1 = document.getElementById('question1');
let question2 = document.getElementById('question2');
let question3 = document.getElementById('question3');
let question4 = document.getElementById('question4');
let question5 = document.getElementById('question5');
let quiz = document.getElementById('quiz');
const start = document.getElementById('startQ');

let generateQuiz = () =>{
    const maxNum = document.getElementById('maxNum').value; //Need to fix this a bit, as it stands now it excludes the maxNumber, not include it but I also want 0 included as well.
    const operation = document.getElementById('operation').value;
    if(maxNum <= 0){
        alert("Please make sure you've entered a max Value greater than 0 and have chosen an operation.")
    }else{
        switch(operation){
            case 'addition':
                for(let i = 0; i < 5; i++){
                    let a = Math.floor(Math.random() * maxNum);
                    let b = Math.floor(Math.random() * maxNum);
                    let q = a + ' + ' + b + ' = ';
                    let an = a + b;
                    let problem = document.createElement('div');
                    problem.setAttribute("id", "problem"); //Okay, the code below works, so I decided not to number the problem divs since it'll make CSS a lot more simple
                    //Below will create a numbered div for each of the 5 problems uising a for loop.  I set it up this way so in the future if I want I can easily expand beyond 5 problems.
                    problem.innerHTML = '<div id ="question' + i + '">' + q + '</div><input type="number" id="sol' + i + ' name="sol' + i + '"><div id="answer' + i +'">' + an + '</div>'
                    quiz.appendChild(problem);
                }
                break;
            //case 'subtraction':
            //case 'multiplication':
            //case 'division' ***Keep this simple for the kids, have one number generated by numMax and the other one be the same number but multiplied by a number between 0 - 5 to start, will attempt to make a Division with Remainders and a Division with decimals later
         
            default: alert("This operation has not been coded yet.")
        }
    }

}

start.addEventListener('click', generateQuiz);